version: "3.8"

x-healthcheck-defaults: &healthcheck_defaults
  interval: 10s  # 间隔
  timeout: 5s  # 超时
  retries: 5  # 连续失败次数
  start_period: 10s # 初始化时间

services:

  webstack-go-service:
    container_name: webstack-go-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - ./configs:/opt/configs
      - ./logs/:/opt/logs/
      - ./assets/upload/:/opt/assets/upload
      - ./lock/:/opt/lock
    network_mode: host
    healthcheck:
      test: "/bin/netstat -anpt|grep 9999"
      <<: *healthcheck_defaults


